spring:
  application:
    name: sboot-login-app
  main:
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
    
server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false
 
#management:
#  server:
#    port: 9090
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: info, health, metrics, prometheus

---
spring:
  profiles: 
    active: local
  datasource:
    url: jdbc:mysql://192.168.0.18:3306/aluradb?useTimezone=true?serverTimezone=UTC?useUnicode=yes?characterEncoding=UTF-8?useSSL=false
    username: alura_user
    password: alura@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver